version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jquery",
    "browser"
  ]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "flow"
